// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoRLrs8syhvQcX76U17TH7UVZ6ryVXSSU',
    appId: '1:322495837903:web:7c05152eb842aa6cc769ba',
    messagingSenderId: '322495837903',
    projectId: 'lucco-fashion-app-dd028',
    authDomain: 'lucco-fashion-app-dd028.firebaseapp.com',
    storageBucket: 'lucco-fashion-app-dd028.firebasestorage.app',
    measurementId: 'G-BKSNL3VL3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgh6_rQTyi2fUmYreLn5Ts5JTEAm9_ros',
    appId: '1:322495837903:android:4188f1d0bdc94006c769ba',
    messagingSenderId: '322495837903',
    projectId: 'lucco-fashion-app-dd028',
    storageBucket: 'lucco-fashion-app-dd028.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKRF_t4HPPRr989K0E4EKNoOQpXAVaTdQ',
    appId: '1:322495837903:ios:d6edb5255459ea67c769ba',
    messagingSenderId: '322495837903',
    projectId: 'lucco-fashion-app-dd028',
    storageBucket: 'lucco-fashion-app-dd028.firebasestorage.app',
    iosBundleId: 'com.example.lucco',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKRF_t4HPPRr989K0E4EKNoOQpXAVaTdQ',
    appId: '1:322495837903:ios:d6edb5255459ea67c769ba',
    messagingSenderId: '322495837903',
    projectId: 'lucco-fashion-app-dd028',
    storageBucket: 'lucco-fashion-app-dd028.firebasestorage.app',
    iosBundleId: 'com.example.lucco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoRLrs8syhvQcX76U17TH7UVZ6ryVXSSU',
    appId: '1:322495837903:web:70248c8d26999da1c769ba',
    messagingSenderId: '322495837903',
    projectId: 'lucco-fashion-app-dd028',
    authDomain: 'lucco-fashion-app-dd028.firebaseapp.com',
    storageBucket: 'lucco-fashion-app-dd028.firebasestorage.app',
    measurementId: 'G-F7NFWLNRLR',
  );
}
